<?php
/**
 * Created by PhpStorm.
 * User: cy
 * Date: 2018/11/9
 * Time: 16:25
 */

namespace app\api\controller\v1;


use app\common\lib\exception\BasicException;
use app\common\model\User;

class BasicAuth extends Common
{
    public $user;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        // 验证token
        $this->checkAccessToken();
    }

    public function checkAccessToken()
    {
        $accessToken = $this->header['access_token'] ?? '';

        if (!$accessToken) {
            throw new BasicException([
                'httpCode' => 401,
                'message' => '未登录',
                'statusCode' => ''
            ]);
        }

        $user = User::get(['token' => $accessToken, 'status' => 1, 'time_out' => ['>', time()]]);
        if (!$user) {
            throw  new BasicException([
               'httpCode' => 401,
               'message' => '请重新登陆',
               'statusCode' => ''
            ]);
        }
        $this->user = $user;
        return true;
    }
}